version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: postgres
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"  # Exposing port for PostgreSQL connection
    networks:
      - mynetwork

  # DynamoDB (Local)
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"  # Exposing port for DynamoDB connection
    networks:
      - mynetwork

  # Spring Boot Application
  myproject:
    build: .
    ports:
      - "8080:8080"  # Exposing port for the Spring Boot app
    depends_on:
      - postgres
      - dynamodb
    networks:
      - mynetwork
    environment:
      SPRING_PROFILES_ACTIVE: docker

networks:
  mynetwork:
    driver: bridge
